### ISSUE TITLE
Cubiescreen with a raspberry pi

### ISSUE THREAD

**Issue by zatarra** [messi1/cubiescreen#1]
Hi,

Sorry for this weird approach but I couldn't find another way of contacting you.  I know that this lcd was created for cubieboards, but I was wondering if you ever tried to do something to make them run on raspberry pies.

Thanks :)

**Comment by messi1** [comment]
Hi
this is not possible because the raspberry pie boards have no such LCD interface.
Rpi only offers one MIPI interface. Either you switch to Cubieboard oder BeagleBoneBlack or you choose the official LCD for the rpi. Best regards

**Comment by zatarra** [comment]
Understood. Thanks for the prompt reply!
